#!/bin/sh

if [ `id -u` !=0 ];then
    echo "Need to be root"
    exit 1
fi

prefix=/root/resume_robot
device=/dev/sda
config=$prefix/config
mbr=$config/mbr
parted=$config/parted.bak
echo "创建分区表信息文件"
echo "克隆$device前信息到文件$mbr"
mkdir -p $config
dd if=$device of=$mbr bs=512 count=1
echo "备份分区表信息到$parted"
sfdisk -d $device > $parted
